
# Site settings
title: Wenxiao Cai
name: Wenxiao Cai
subtitle:  Engineer
email: robincwx@foxmail.com
description: >
   Economist
baseurl: ""
url: "https://russrobin.github.io"
github_username:  russrobin
disqus_baseurl: "https://russrobin.github.io"
disqus_shortname: https-russrobin-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Wenxiao Cai"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: RussRobin
    url: https://github.com/RussRobin
    desc: Fork me on GitHub
    share: false

